### ISSUE TITLE
Deploy build is broken

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#499] opened 2017-04-14 20:39 UTC
I dunno why but build for deploying stuff is broken - https://travis-ci.org/marionettejs/marionettejs.com/builds/220112384

Everything built fine until script wanna init git, add files and push all stuff to gh-pages.

Last time I did deploy manually using `ship.sh` script.

**Comment by denar90** [comment] 2017-05-10 21:21
So I made pushing stuff in `travis-runner.sh` kinda same as `ship.sh` and now error say smth we can think about https://travis-ci.org/marionettejs/marionettejs.com/builds/230931875#L1268
```
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/marionettejs/marionettejs.com.git/'
```

**Comment by paulfalgout** [comment] 2017-05-11 08:24
Fixed the deploy by redoing the gh_token, but now it won't compile the docs

**Comment by denar90** [comment] 2017-05-11 08:38
I suppose it's because of https://github.com/marionettejs/marionettejs.com/commit/1bb5e1754e87f5c2f4aff4b4625d079ec99061f0#diff-354f30a63fb0907d4ad57269548329e3L15
we should either bring back yarn or add npm i

**Comment by paulfalgout** [comment] 2017-05-11 08:46
`yarn` was being called twice as travis will install it or call it automatically.

**Comment by paulfalgout** [comment] 2017-05-11 09:08
Pretty sure the travis script's GH_TOKEN was getting overwritten by:
```
Setting environment variables from .travis.yml
$ export GIT_NAME=[secure]
$ export GIT_EMAIL=[secure]
$ export GH_TOKEN=[secure]
```

When I renamed the one in travis to `GITHUB_TOKEN` the script started working, but the docs wouldn't compile

**Comment by paulfalgout** [comment] 2017-05-11 09:10
I re-added `GH_TOKEN` a duplicate of `GITHUB_TOKEN` to travis, but no change.. 
All I'm getting now is:
```
Running "gitty:checkoutTag:marionette" (gitty:checkoutTag) task
>> Tag Checked out! -- undefined
```

**Comment by paulfalgout** [comment] 2017-05-11 09:21
I definitely think this issue is related to the GH info being added in this env var: https://github.com/marionettejs/marionettejs.com/blob/master/.travis.yml#L6 in addition to being set in travis itself.

Note I also put back `yarn` getting called and installed twice.

**Comment by denar90** [comment] 2017-05-24 15:36
I've been told that gh retrieved tokens after some security leak or smth. But I dunno why token generated by me won't work...

So, can we close this one?

**Comment by paulfalgout** [comment] 2019-05-23 06:02
Out of all of the things currently broken on the website, this is not one :-)

**Closed by paulfalgout** 2019-05-23 06:02 UTC
